spring.application.name=provider
server.port=8443

server.ssl.enabled=true

server.ssl.key-store=classpath:skoda-server.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=server

#myCa mastercard.crt adidas.crt KPMG.crt sab ki files hoti -- it asks to provide the cert for the verifiate.
server.ssl.trust-store=classpath:truststore.p12
server.ssl.trust-store-password=password
server.ssl.trust-store-type=PKCS12

#Every client must present a valid client certificate
server.ssl.client-auth=need